Repository IvorySQL/IvorySQL, pull requests merged in 2023-09, with the labels that each got.

#480 IvorySQL:When the year in the time format is RRRR, the data processing of the year exceeding 4 digits is inconsistent with oracle
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
Labels: bug, 3.0, Community

#476 PL/iSQL not support %rowtype #475
  src/backend/oracle_parser/ora_gram.y
  src/include/oracle_parser/ora_kwlist.h
  src/oracle_test/regress/expected/ora_plisql.out
  src/oracle_test/regress/sql/ora_plisql.sql
Labels: enhancement, 3.0, Community

#481 add compatible test case
  contrib/file_fdw/expected/ivy_file_fdw.out
  contrib/file_fdw/sql/ivy_file_fdw.sql
  contrib/ltree/expected/ivy_ltree.out
  contrib/ltree/sql/ivy_ltree.sql
  contrib/pageinspect/Makefile
  contrib/pageinspect/expected/ivy_brin.out
  contrib/pageinspect/expected/ivy_gin.out
  contrib/pageinspect/expected/ivy_gist.out
  contrib/pageinspect/expected/ivy_hash.out
  contrib/pageinspect/expected/ivy_oldextversions.out
  contrib/pageinspect/expected/ivy_page.out
  contrib/pageinspect/sql/ivy_brin.sql
  contrib/pageinspect/sql/ivy_gin.sql
  contrib/pageinspect/sql/ivy_gist.sql
  contrib/pageinspect/sql/ivy_hash.sql
  contrib/pageinspect/sql/ivy_oldextversions.sql
  contrib/pageinspect/sql/ivy_page.sql
  contrib/pg_trgm/expected/ivy_pg_trgm.out
  contrib/pg_trgm/sql/ivy_pg_trgm.sql
  contrib/pg_visibility/Makefile
  contrib/pg_visibility/expected/ivy_pg_visibility.out
  contrib/pg_visibility/sql/ivy_pg_visibility.sql
  contrib/postgres_fdw/expected/ivy_postgres_fdw.out
  contrib/postgres_fdw/sql/ivy_postgres_fdw.sql
  contrib/xml2/expected/ivy_xml2_1.out
Labels: enhancement, 3.0, Community

#488 call wrong function
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  contrib/ivorysql_ora/src/builtin_functions/builtin_functions--1.0.sql
Labels: bug, 3.0, Community, CR

#492 IvorySQL PL/SQL 创建函数/存储过程存在问题 #477
  src/include/fe_utils/psqlscan_int.h
  src/oracle_fe_utils/ora_psqlscan.l
Labels: enhancement, 3.0, Community, CR

#491 select sys.length fail
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  contrib/ivorysql_ora/src/builtin_functions/builtin_functions--1.0.sql
Labels: bug, 3.0, Community, CR

#490 IvorySQL:Run make oracle-check without ICU and some use cases fail
  src/oracle_test/regress/expected/char_1.out
  src/oracle_test/regress/expected/collate.icu.utf8.out
  src/oracle_test/regress/expected/varchar_1.out
Labels: bug, 3.0, Community, CR

#498 When you alter the properties of a table to identity column, you can also modify the identity column
  src/backend/commands/sequence.c
  src/backend/oracle_parser/ora_gram.y
  src/oracle_test/regress/expected/identity.out
  src/oracle_test/regress/expected/sequence.out
  src/oracle_test/regress/sql/identity.sql
Labels: bug, 3.0, Community, CR

#500 There are some inappropriate changes in PR#494, so this patch is used for repair.
  contrib/citext/expected/ivy_citext.out
  contrib/citext/expected/ivy_citext_1.out
  contrib/postgres_fdw/expected/ivy_postgres_fdw_1.out
  src/backend/utils/adt/format_type.c
  src/oracle_test/regress/expected/create_view.out
  src/oracle_test/regress/expected/date.out
  src/oracle_test/regress/expected/opr_sanity.out
  src/oracle_test/regress/expected/psql.out
  src/test/regress/expected/opr_sanity_1.out
Labels: bug, 3.0, Community, CR

#503 change the Modify file:*.po encoding format
  src/pl/plisql/src/po/ja.po
  src/pl/plisql/src/po/ko.po
  src/pl/plisql/src/po/vi.po
  src/pl/plisql/src/po/zh_CN.po
  src/pl/plisql/src/po/zh_TW.po
Labels: bug, 3.0, Community, CR

#508 IvorySQL:initdb --help less -m info
  src/bin/initdb/initdb.c
Labels: bug, 3.0, Community, CR

#501 IvorySQL:The operator result of a character type null value is incorrect
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/expected/ora_sysview.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  contrib/ivorysql_ora/sql/ora_sysview.sql
  contrib/ivorysql_ora/src/datatype/datatype--1.0.sql
Labels: bug, 3.0, Community, CR

#507 Data type is binary_float, data is partially inserted, and the result is wrong
  contrib/ivorysql_ora/expected/ora_binary_float.out
  contrib/ivorysql_ora/sql/ora_binary_float.sql
  contrib/ivorysql_ora/src/datatype/binary_float.c
Labels: bug, 3.0, Community, CR

#510 IvorySQL:Support meson build
  contrib/ivorysql_ora/Makefile
  contrib/ivorysql_ora/gensql.pl
  contrib/ivorysql_ora/meson.build
  contrib/meson.build
  contrib/ora_btree_gin/meson.build
  contrib/ora_btree_gist/meson.build
  meson.build
  meson_options.txt
  src/backend/catalog/meson.build
  src/backend/meson.build
  src/backend/oracle_parser/meson.build
  src/backend/utils/misc/meson.build
  src/bin/psql/meson.build
  src/fe_utils/meson.build
  src/include/catalog/meson.build
  src/include/catalog/pg_type.dat
  src/include/meson.build
  src/meson.build
  src/oracle_fe_utils/meson.build
  src/oracle_test/isolation/meson.build
  src/oracle_test/perl/meson.build
  src/oracle_test/regress/meson.build
  src/pl/plisql/src/meson.build
  src/port/meson.build
Labels: enhancement, 3.0

#513 fix date fail
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
Labels: bug, 3.0, Community, CR

#515 IvorySQL:Add the meson build to the action
  .github/workflows/meson_build.yml
Labels: 3.0, Community

#519 IvorySQL:Fix the issue of ora_btree_gist plugin failing to compile on MacOS system.
  GNUmakefile.in
  contrib/ora_btree_gin/data/timestamptz.data
  contrib/ora_btree_gin/ora_btree_gin.c
  contrib/ora_btree_gist/btree_binary_double.c
  contrib/ora_btree_gist/btree_binary_float.c
  contrib/ora_btree_gist/btree_dsinterval.c
  contrib/ora_btree_gist/btree_gist.c
  contrib/ora_btree_gist/btree_interval.c
  contrib/ora_btree_gist/btree_number.c
  contrib/ora_btree_gist/btree_timestamp.c
  contrib/ora_btree_gist/btree_utils_num.c
  contrib/ora_btree_gist/btree_utils_var.c
  contrib/ora_btree_gist/btree_varcharchar.c
  contrib/ora_btree_gist/btree_yminterval.c
Labels: bug, 3.0

#521 IvorySQL:After compiling with meson, the execution of the 'initdb' command failed.
  contrib/ivorysql_ora/meson.build
Labels: bug, 3.0
