Repository IvorySQL/IvorySQL, pull requests merged in 2023-08, with the labels that each got.

#335 fix the error of 'fix the bug of pg_basebackup'
  src/fe_utils/recovery_gen.c
Labels: bug, 3.0

#350 IvorySQL:fix compatible extension amcheck
  contrib/amcheck/Makefile
  contrib/amcheck/expected/ivy_check_heap.out
  contrib/amcheck/sql/ivy_check_heap.sql
Labels: bug, 3.0

#374 IvorySQL:compatible extension cube
  contrib/cube/Makefile
  contrib/cube/expected/ivy_cube.out
  contrib/cube/sql/ivy_cube.sql
Labels: enhancement, 3.0, Community

#377 IvorySQL:compatible extension fuzzystrmatch
  contrib/fuzzystrmatch/Makefile
  contrib/fuzzystrmatch/expected/ivy_fuzzystrmatch.out
  contrib/fuzzystrmatch/sql/ivy_fuzzystrmatch.sql
Labels: enhancement, 3.0

#380 IvorySQL:compatible extension hstore
  contrib/hstore/Makefile
  contrib/hstore/expected/ivy_hstore.out
  contrib/hstore/sql/ivy_hstore.sql
Labels: enhancement, 3.0, Community

#382 IvorySQL:compatible extension ltree
  contrib/ltree/Makefile
  contrib/ltree/expected/ivy_ltree.out
  contrib/ltree/sql/ivy_ltree.sql
Labels: bug, 3.0, Community

#383 IvorySQL:compatible extension ltree_plpython
  contrib/ltree_plpython/Makefile
  contrib/ltree_plpython/expected/ivy_ltree_plpython.out
  contrib/ltree_plpython/sql/ivy_ltree_plpython.sql
Labels: enhancement, 3.0, Community

#384 IvorySQL:compatible extension pg_trgm
  contrib/pg_trgm/Makefile
  contrib/pg_trgm/expected/ivy_pg_trgm.out
  contrib/pg_trgm/sql/ivy_pg_trgm.sql
Labels: enhancement, 3.0, Community

#385 IvorySQL:compatible extension uuid-ossp
  contrib/uuid-ossp/Makefile
  contrib/uuid-ossp/expected/ivy_uuid_ossp.out
  contrib/uuid-ossp/sql/ivy_uuid_ossp.sql
Labels: enhancement, 3.0, Community

#393 IvorySQL:compatible extension bool_plperl
  contrib/bool_plperl/Makefile
  contrib/bool_plperl/expected/ivy_bool_plperl.out
  contrib/bool_plperl/expected/ivy_bool_plperlu.out
  contrib/bool_plperl/sql/ivy_bool_plperl.sql
  contrib/bool_plperl/sql/ivy_bool_plperlu.sql
Labels: enhancement, 3.0, Community

#396 IvorySQL:compatible extension pageinspect
  contrib/pageinspect/pageinspect--1.11--1.12.sql
  contrib/pageinspect/pageinspect--1.5.sql
  contrib/pageinspect/pageinspect--1.8--1.9.sql
Labels: bug, 3.0, Community

#407 IvorySQL:compatible extension hstore_plperl
  contrib/hstore_plperl/Makefile
  contrib/hstore_plperl/expected/ivy_create_transform.out
  contrib/hstore_plperl/expected/ivy_hstore_plperl.out
  contrib/hstore_plperl/expected/ivy_hstore_plperlu.out
  contrib/hstore_plperl/sql/ivy_create_transform.sql
  contrib/hstore_plperl/sql/ivy_hstore_plperl.sql
  contrib/hstore_plperl/sql/ivy_hstore_plperlu.sql
Labels: enhancement, 3.0, Community

#420 After changing the NLS time format, the SYSDATE query prompt is not supported
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
Labels: bug, 3.0, Community

#417 IvorySQL:Split the sql file in the extension ivorysql_ora
  contrib/ivorysql_ora/Makefile
  contrib/ivorysql_ora/gensql.pl
  contrib/ivorysql_ora/ivorysql_ora_merge_sqls
  contrib/ivorysql_ora/src/builtin_functions/builtin_functions--1.0.sql
  contrib/ivorysql_ora/src/datatype/datatype--1.0.sql
  contrib/ivorysql_ora/src/sysview/sysview--1.0.sql
  src/oracle_test/regress/expected/strings.out
  src/tools/msvc/Solution.pm
  src/tools/msvc/clean.bat
Labels: enhancement, 3.0, Community

#418 IvorySQL:compatible extension seg
  contrib/seg/Makefile
  contrib/seg/expected/ivy_security.out
  contrib/seg/expected/ivy_seg.out
  contrib/seg/sql/ivy_security.sql
  contrib/seg/sql/ivy_seg.sql
Labels: enhancement, 3.0, Community

#422 IvorySQL:compatible extension tablefunc
  contrib/tablefunc/Makefile
  contrib/tablefunc/expected/ivy_tablefunc.out
  contrib/tablefunc/sql/ivy_tablefunc.sql
Labels: enhancement, 3.0, Community

#424 IvorySQL:After changing the NLS time format, SYSTIMESTAMP does not display thetime according to the prescribed format
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
Labels: bug, 3.0, Community

#425 IvorySQL:compatible extension test_decoding
  contrib/test_decoding/Makefile
  contrib/test_decoding/expected/ivy_concurrent_ddl_dml.out
  contrib/test_decoding/expected/ivy_ddl.out
  contrib/test_decoding/expected/ivy_decoding_into_rel.out
  contrib/test_decoding/expected/ivy_rewrite.out
  contrib/test_decoding/expected/ivy_slot.out
  contrib/test_decoding/expected/ivy_time.out
  contrib/test_decoding/expected/ivy_toast.out
  contrib/test_decoding/specs/ivy_concurrent_ddl_dml.spec
  contrib/test_decoding/sql/ivy_ddl.sql
  contrib/test_decoding/sql/ivy_decoding_into_rel.sql
  contrib/test_decoding/sql/ivy_rewrite.sql
  contrib/test_decoding/sql/ivy_slot.sql
  contrib/test_decoding/sql/ivy_time.sql
  contrib/test_decoding/sql/ivy_toast.sql
  src/makefiles/pgxs.mk
Labels: enhancement, 3.0, Community

#423 IvorySQL:compatible extension pg_stat_statements
  contrib/pg_stat_statements/Makefile
  contrib/pg_stat_statements/expected/ivy_dml.out
  contrib/pg_stat_statements/expected/ivy_level_tracking.out
  contrib/pg_stat_statements/expected/ivy_utility.out
  contrib/pg_stat_statements/sql/ivy_dml.sql
  contrib/pg_stat_statements/sql/ivy_level_tracking.sql
  contrib/pg_stat_statements/sql/ivy_utility.sql
Labels: enhancement, 3.0, Community

#427 IvorySQL:compatible extension postgres_fdw
  contrib/postgres_fdw/Makefile
  contrib/postgres_fdw/expected/ivy_postgres_fdw.out
  contrib/postgres_fdw/sql/ivy_postgres_fdw.sql
Labels: enhancement, 3.0, Community

#428 support ORA_ISOLATION
  contrib/pgrowlocks/Makefile
  contrib/tcn/Makefile
Labels: enhancement, 3.0, Community

#406 IvorySQL:compatible extension citext
  contrib/citext/Makefile
  contrib/citext/expected/ivy_citext.out
  contrib/citext/expected/ivy_citext_1.out
  contrib/citext/expected/ivy_create_index_acl.out
  contrib/citext/sql/ivy_citext.sql
  contrib/citext/sql/ivy_create_index_acl.sql
Labels: enhancement, 3.0, Community

#438 IvorySQL:compatible extension btree_gin
  contrib/btree_gin/Makefile
  contrib/btree_gin/btree_gin--1.0.sql
Labels: enhancement, 3.0, Community

#443 IvorySQL:compatible extension btree_gist
  contrib/btree_gist/Makefile
  contrib/btree_gist/btree_gist--1.0--1.1.sql
  contrib/btree_gist/btree_gist--1.1--1.2.sql
  contrib/btree_gist/btree_gist--1.2.sql
  contrib/btree_gist/btree_gist--1.5--1.6.sql
Labels: enhancement, 3.0, Community, CR

#444 IvorySQL:Insertion of data into interval '1- 11' year to month failed, Oracle succeeded
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  contrib/ivorysql_ora/src/datatype/yminterval.c
Labels: bug, 3.0, Community, CR

#447 In the YY format, the data processing logic for the year is inconsistent with that of oracle
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
Labels: bug, 3.0, Community, CR

#453 IvorySQL:add contrib regression
  .github/workflows/contrib_regression.yml
Labels: enhancement, 3.0, CR

#449 IvorySQL:The NLS parameter is set to 12-hour clock, and the default rule for completing AM/PM keywords is inconsistent with Oracle
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
Labels: bug, 3.0, Community, CR

#454 IvorySQL:Returning the number of times a pattern occurs in a source string
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  contrib/ivorysql_ora/src/builtin_functions/character_datatype_functions.c
Labels: enhancement, 3.0, Community, CR

#457 IvorySQL:Modify the use of decode in functions
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/expected/ora_misc_functions.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  src/backend/optimizer/util/clauses.c
  src/backend/parser/parse_expr.c
Labels: enhancement, 3.0, Community, CR

#458 IvorySQL:Auto-increment syntax supports empty options
  src/backend/oracle_parser/ora_gram.y
  src/oracle_test/regress/expected/identity.out
  src/oracle_test/regress/sql/identity.sql
Labels: bug, 3.0, Community

#463 IvorySQL:binary_double/binary_float not supported Special values.
  contrib/ivorysql_ora/expected/ora_binary_double.out
  contrib/ivorysql_ora/expected/ora_binary_float.out
  contrib/ivorysql_ora/sql/ora_binary_double.sql
  contrib/ivorysql_ora/sql/ora_binary_float.sql
  src/backend/oracle_parser/ora_gram.y
  src/include/oracle_parser/ora_kwlist.h
Labels: bug, 3.0, Community

#465 IvorySQL:Inserting null values into identity column of number type with specified precision
  src/backend/rewrite/rewriteHandler.c
  src/oracle_test/regress/expected/identity.out
  src/oracle_test/regress/sql/identity.sql
Labels: bug, 3.0, Community

#464 IvorySQL:'merge into' include custom function error
  contrib/ivorysql_ora/expected/ora_merge.out
  contrib/ivorysql_ora/sql/ora_merge.sql
  contrib/ivorysql_ora/src/merge/ora_merge.c
  src/backend/parser/parse_expr.c
  src/include/parser/parse_node.h
Labels: bug, 3.0, Community

#467 IvorySQL:Fix ivorysql_ora extension test case fail
  contrib/ivorysql_ora/Makefile
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/expected/ora_sysview.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  contrib/ivorysql_ora/sql/ora_sysview.sql
  contrib/ivorysql_ora/src/builtin_functions/builtin_functions--1.0.sql
  src/makefiles/pgxs.mk
  src/oracle_test/regress/expected/strings_1.out
  src/oracle_test/regress/sql/strings.sql
Labels: bug, 3.0, Community

#459 IvorySQL:fix issue #433, #434, #435, #436
  contrib/ivorysql_ora/expected/ora_datetime.out
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
  src/oracle_test/regress/expected/date.out
  src/oracle_test/regress/expected/horology.out
  src/oracle_test/regress/expected/timestamp.out
  src/oracle_test/regress/expected/timestamptz.out
  src/oracle_test/regress/expected/xmlmap.out
Labels: bug, 3.0, CR

#471 IvorySQL:calculates strings using bytes instead of characters
  contrib/ivorysql_ora/expected/ora_character_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_character_datatype_functions.sql
  contrib/ivorysql_ora/src/builtin_functions/builtin_functions--1.0.sql
  contrib/ivorysql_ora/src/builtin_functions/character_datatype_functions.c
Labels: bug, 3.0, Community

#474 IvorySQL:create view tv as select * from test WITH LOCAL CHECK OPTION' fail
  src/backend/oracle_parser/liboracle_parser.c
  src/oracle_test/regress/expected/updatable_views.out
Labels: bug, 3.0, Community

#478 IvorySQL:When the year in the time format is RR, the data processing for the year exceeding 2 digits is inconsistent with oracle
  contrib/ivorysql_ora/expected/ora_datetime_datatype_functions.out
  contrib/ivorysql_ora/sql/ora_datetime_datatype_functions.sql
  src/backend/utils/adt/formatting.c
Labels: bug, 3.0, Community
